CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL
);

CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255),
                          description TEXT,
                          price NUMERIC(19, 2) NOT NULL,
                          quantity INT NOT NULL,
                          deleted BOOLEAN NOT NULL DEFAULT FALSE,
                          created_at TIMESTAMP,
                          updated_at TIMESTAMP
);

CREATE INDEX idx_products_deleted ON products (deleted);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        order_total NUMERIC(19, 2),
                        CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             quantity INT NOT NULL,
                             unit_price NUMERIC(19, 2) NOT NULL,
                             discount_applied NUMERIC(19, 2),
                             total_price NUMERIC(19, 2),
                             CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);
